---
services:
  plex:
    image: gradio-app
    container_name: gradio-app
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${PWD}:/workspace
    restart: unless-stopped
    ports:
      - 7868:7868
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gradio.rule=Host(`gradio.frabeamar.uk`)"
      - "traefik.http.routers.gradio.entrypoints=https"
      - "traefik.http.routers.gradio.tls=true"
      - "traefik.http.routers.gradio.tls.certresolver=leresolver"
      - "traefik.http.services.gradio.loadbalancer.server.port=7868"
    networks:
      - proxy
      
networks:
  proxy:
    external: true

